name: Pull Request Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate Environment Variables File
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> .env
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env
          echo "NEXT_AUTH_SECRET=$NEXT_AUTH_SECRET" >> .env
          echo "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID" >> .env
          echo "GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET" >> .env
          echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID" >> .env
          echo "CLOUDFLARE_IMAGE_API_TOKEN=$CLOUDFLARE_IMAGE_API_TOKEN" >> .env
          echo "NEXT_PUBLIC_IMAGE_SERVE_URL=$NEXT_PUBLIC_IMAGE_SERVE_URL" >> .env
          echo "TEST_USER_ID=$TEST_USER_ID" >> .env
          echo "TEST_USER_NICKNAME=$TEST_USER_NICKNAME" >> .env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXT_AUTH_SECRET: ${{ secrets.NEXT_AUTH_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.HUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.HUB_CLIENT_SECRET }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_IMAGE_API_TOKEN: ${{ secrets.CLOUDFLARE_IMAGE_API_TOKEN }}
          NEXT_PUBLIC_IMAGE_SERVE_URL: ${{ secrets.NEXT_PUBLIC_IMAGE_SERVE_URL }}
          TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
          TEST_USER_NICKNAME: ${{ secrets.TEST_USER_NICKNAME }}
      - name: Lint / Test / Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn lint
          yarn test
          yarn build
        env:
          CI: true
